### ISSUE TITLE
Jingles buttons color (change)

### ISSUE THREAD

**Issue by CouinCouin** [nagyrobi/Jingle_Palette#2]
Hi :) 

I'm doing some custom modification so I would change the jingle buttons color (for a future palette.ini color saving per jingle). 

I found where to change color : 
- while pressing button (in modMain -> Public Sub btClic  )
- while jingle is playing (in frmMain -> Private Sub b_Jingle_Click )
- when jingle has been played ( in frmMain -> Private Sub Timer5_Timer() ) (but resets to grey when changing palette). 

I encounter a first problem :  the colored button while playing/pressing, looks strange, like mixed with white color . With certain color codes, it looks mixed white + dotted. 
For example , I set : 
`b_Jingle(Index).BackColor = vbBlue`
instead of 
`b_Jingle(Index).BackColor = &HC0FFC0`
I get this :
![image](https://user-images.githubusercontent.com/62549730/98894633-7a994180-24a5-11eb-94f0-5223b223641a.png)

From where come's this mixing + doting colors ? 

 ======

My second problem : I don't find where is defined the button default color.  For example, in frmMain > Private Sub lstpal_Click() I add : 
```
            For i = 0 To 29
               b_Jingle(i).backColor = vbRed
            Next i
```
The all buttons blinks red on each palette change , but stil colored in grey. 

Where can I change the jingle buttons color ?  

Thanks :)
Couin

**Comment by nagyrobi** [comment]
Oh boy... I haven't touched this code for at least 15 years. I hardly remember what's inthere...

As far as I remember `vbBlue`, `vbRed` and similar are factory-defined Visual Basic constants so these don't have to be defined in the code. Mixed white+dotted is something Visual Basic makes on its own, I don't control that separately. For that color code, that's how it looks like, and back then I considered that good enough.
There's a routine somewhere which takes care to return to grey, which is `vbButtonFace` system color constant, after work is done with the button.
So I suppose all that you should to, is to define the return to your specific color after handling the button, instead of returning to `vbButtonFace`.

**Comment by CouinCouin** [comment]
Hi dear

I'm aware that is an oooold code, I use Jingle Palette since several years, I like it :)
About vbRed , vbBlue etc etc, I notice the same behavior (mixed white + dotted) even if I set a RGB color or something like &HFF0000 (for Red). 
Also, this mixed/dotted problem doesn't appears in all programm cases. I mean, for example, in Timer5, if a replace 
`b_Jingle(k).BackColor = vbButtonFace`
by
`b_Jingle(k).BackColor = vbRed`
The button returns Red once jingle played, with the mixed/dotted problem. 

About the buttons color, the modification in Timer5 runs only after jingle played, but not on program load or palette change. 
It should problably inb another place lol 
Still searching for this (but if you have some idea, it will be welcome ^^ ) 

Thanks :D

**Comment by nagyrobi** [comment]
The development of this program was started on Windows 2000, and continued and finsihed on Windows XP, don't forget. Colors were different back then.

**Comment by CouinCouin** [comment]
Hi dear, 

I think it's not an OS version problem but I think I found why, it's because the buttons are not buttons but graphical checkboxes, I can obtain the same behavior : 
![unchecked](https://user-images.githubusercontent.com/62549730/99682911-0c91e300-2a80-11eb-837c-d36f34ff9958.jpg)

**Comment by nagyrobi** [comment]
Yes that's true, they are button-looking ckeckboxes. This is because normal buttons can never stay pressed in VB6.

**Comment by CouinCouin** [comment]
I will have to find a trick :)
