### ISSUE TITLE
makensis.exe, really  ? 

### ISSUE THREAD

**Issue by CouinCouin** [nagyrobi/Jingle_Palette#6]
Hi dear, 

As well a friend hard testing versions I build with new features and improvements of Jingle Palette, we are asking ourselves the utility of copying makensis.exe in the app dir on install ? 
We noticed Jingle Palette runs normally even this file deleted but perhaps used for another function ?  

Thanks for infos :) 
Have e nice day 
Couin

**Comment by nagyrobi** [comment]
It was used to build the installer, and also as a helper for Windows's Add/Remove programs uninstaller functionality.

**Comment by CouinCouin** [comment]
Thanks :)
