### ISSUE TITLE
Difference of exe files size

### ISSUE THREAD

**Issue by CouinCouin** [nagyrobi/Jingle_Palette#7]
Hi :) 

Just a small question, I see in the project files, a jingle_palette.exe of 91 KB, and Jingle_Palette_Vb.exe of 376 KB. 

If you remember, how do you obtain a small file like this ?  

Thanks :D 
Couin

**Comment by nagyrobi** [comment]
As far as I remember, I used an UPX exe compressor tool to make it smaller. Look at `compress_copy_dist.bat`

**Comment by CouinCouin** [comment]
Hi dear, 

Thanks , I was that ! Just tried with success ! :)

In this case, I can close the thread. 

See ya ! 
Couin
